server:
  port: 8081

spring:
  application:
    name: base-service
  messages:
    basename: message
    fallback-to-system-locale: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost
