server:
  port: 8081

spring:
  application:
    name: base-service
  r2dbc:
    url: r2dbc:postgresql://postgres:admin@localhost:5432/tenant_1
  messages:
    basename: message
    fallback-to-system-locale: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost
